### ISSUE TITLE
LUA error - First Aid

### ISSUE THREAD

**Issue by Painstormx** [teelolws/Altoholic-Classic#10]
A bit of a weird issue, but the 2nd time I click the First Aid profession, I get the error below.
It doesn't seem to happen for other professions.

Date: 2020-02-09 21:40:34
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua line 287:
   attempt to perform arithmetic on field '?' (a nil value)
Debug:
   (tail call): ?
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:287:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:284
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:355:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:301
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:457:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:456
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:519:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:462
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:543:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:537
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: ?
   [C]: UseAction()
   ..\FrameXML\SecureTemplates.lua:338: handler()
   ..\FrameXML\SecureTemplates.lua:616: SecureActionButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:

**Comment by teelolws** [comment]
Thaoky published his version of Altoholic Classic a few hours ago. Check that one out.

**Comment by teelolws** [comment]
I'll investigate this issue tomorrow.

**Comment by teelolws** [comment]
Looks like I fixed this while merging in Thaoky's changes. He added a column for Fishing and I'm going to add tracking its skill value.
