### ISSUE TITLE
\Characters\Professions\ not finding matching professions ... all the time

### ISSUE THREAD

**Issue by rbpaiett** [teelolws/Altoholic-Classic#11]
When I click on \Characters\Professions\Blacksmithing I get Cooking

When I click on \Characters\Professions\Cooking sometimes I get cooking, sometimes I get blacksmithing

When I click on \Characters\Professions\First Aid I get Blacksmithing 

 

Its so erratic that I can't get a consistent error but basically the menus aren't matching the professions.

== This was posted on the 'other' addon page so I hope this isn't a double-posting.

**Comment by teelolws** [comment]
Yeah this is a problem with the way Altoholic_Summary redirects to search results and its on my long list of broken classic things to fix.

**Comment by teelolws** [comment]
Should be sorted now.
