### ISSUE TITLE
Gathering Profession Tracked Twice

### ISSUE THREAD

**Issue by Natsulus** [teelolws/Altoholic-Classic#15]
Gathering Professions seems to be tracked for both Profession 1 & 2.
I have some characters with a Gathering Profession and a Crafting Profession, but the addon seems to be tracking the Gathering Profession for both Profession slots and ignoring that I have a Crafting Profession.
![Screenshot_48](https://user-images.githubusercontent.com/7202306/75089054-fadee600-55a8-11ea-9553-4e0989559426.png)

**Comment by teelolws** [comment]
Ugh. Thought I fixed that. I'll look into it tomorrow.

**Comment by teelolws** [comment]
Didn't happen on any of the characters I tested, so I suspect this is just bad data saved from a previous version of the addon when I was still working on it.

Either way, I've added a check for whether they're the same. If they are, it deletes the second one. Can you test the latest build and let me know if that fixed this?

**Comment by Natsulus** [comment]
Strange, I only started using this addon with v011 so it shouldn't be bad data.
I've gone and downloaded the updated DataStore_Crafts.lua and replaced it.
When I open up my Blacksmith menu I get:
>Date: 2020-02-23 11:21:52
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua line 397:
   attempt to index global 'char' (a nil value)
Debug:
   (tail call): ?
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:397:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:392
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:500:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:492
   [C]: ?
   ...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...s\AddOnSkins\Libs\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...s\AddOnSkins\Libs\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: ExpandTradeSkillSubClass()
   +Wowhead_Looter\Wowhead_Looter.lua:3079: wlScanTradeSkillWindow()
   +Wowhead_Looter\Wowhead_Looter.lua:2947: ?()
   +Wowhead_Looter\Wowhead_Looter.lua:3782:
      +Wowhead_Looter\Wowhead_Looter.lua:378

So I tried to disable all my other addons, but I still get:

>Date: 2020-02-23 11:26:58
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua line 397:
   attempt to index global 'char' (a nil value)
Debug:
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:397:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:392
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:500:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:492
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119

**Comment by teelolws** [comment]
Right. This is why I should test my code before I upload it. Try again now.

**Comment by Natsulus** [comment]
Fix works.
![Screenshot_56](https://user-images.githubusercontent.com/7202306/75101546-31147800-5632-11ea-87f5-a26f60206028.png)
