### ISSUE TITLE
Only 1 mail displayed

### ISSUE THREAD

**Issue by Natsulus** [teelolws/Altoholic-Classic#16]
> Date: 2020-02-22 19:26:29
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\Altoholic_Characters\Frames\Mails.lua line 122:
   attempt to index local 'itemButton' (a nil value)
Debug:
   [C]: ?
   ...terface\AddOns\Altoholic_Characters\Frames\Mails.lua:122: Update()
   ...erface\AddOns\Altoholic_Characters\TabCharacters.lua:137: ShowCharInfo()
   ...erface\AddOns\Altoholic_Characters\TabCharacters.lua:110: ViewCharInfo()
   ...erface\AddOns\Altoholic_Characters\TabCharacters.lua:344: func()
   ..\FrameXML\UIDropDownMenu.lua:958: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1

![Screenshot_49](https://user-images.githubusercontent.com/7202306/75089223-dab02680-55aa-11ea-9ca5-6754b7305794.png)

**Comment by teelolws** [comment]
Can you upload your \_classic_\WTF\Account\_ACCOUNTNAME_\SavedVariables\DataStore_Mails.lua file please?

**Comment by teelolws** [comment]
There is some code that works on the Retail version that isn't working on Classic, where it calls a function called ItemIconTexture. I can't find where it comes from, on either version, so I'm a bit stuck on this at the moment.

**Comment by teelolws** [comment]
Got it. ItemButton didn't exist until 8.1.5, and Classic is based on Legion. Should be working now.

**Comment by Natsulus** [comment]
Fixed.
![Screenshot_57](https://user-images.githubusercontent.com/7202306/75103164-4c3fb180-564b-11ea-811d-040e32ed26cb.png)
