### ISSUE TITLE
Datastore_Crafts issue with making poisons.

### ISSUE THREAD

**Issue by rbpaiett** [teelolws/Altoholic-Classic#18]
I got this error when crafting poisons.  I think it happens when a char is leveling up:

5x DataStore_Crafts\DataStore_Crafts-r83.lua:233: attempt to perform arithmetic on field '?' (a nil value)
DataStore_Crafts\DataStore_Crafts-r83.lua:233: in function <DataStore_Crafts\DataStore_Crafts.lua:230>
DataStore_Crafts\DataStore_Crafts-r83.lua:292: in function <DataStore_Crafts\DataStore_Crafts.lua:244>
DataStore_Crafts\DataStore_Crafts-r83.lua:394: in function <DataStore_Crafts\DataStore_Crafts.lua:393>
DataStore_Crafts\DataStore_Crafts-r83.lua:551: in function <DataStore_Crafts\DataStore_Crafts.lua:546>
[C]: ?
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Hopefully this is helpful and not just a bunch of gobbledygook.

**Comment by teelolws** [comment]
Got it and fixed it. Grab the fix from the main page here; I won't be able to upload it onto Curseforge for a while.

I'm guessing something similar will happen for Hunters with Beast Training but I don't have a hunter so I can't check that out.

**Comment by rbpaiett** [comment]
So far I haven't had any issues with my hunter as yet.
