### ISSUE TITLE
LUA error when crafting rogue poisons

### ISSUE THREAD

**Issue by Painstormx** [teelolws/Altoholic-Classic#19]
When I craft Instant Poison II, I get the error below after the first item is crafted.
Crafting still continues and everything else seems to work okay.
Altoholic v1.13.013.

Date: 2020-03-14 11:36:51
ID: 1
Error occured in: Global
Count: 3
Message: ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua line 233:
   attempt to perform arithmetic on field '?' (a nil value)
Debug:
   (tail call): ?
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:233:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:230
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:292:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:244
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:394:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:393
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:551:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:546
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None

**Comment by teelolws** [comment]
This is an issue that was fixed already. The fix just isn't up on Curseforge yet. Grab the latest files on the main project page here.

![image](https://user-images.githubusercontent.com/49792789/76680592-a92cf700-664e-11ea-8955-fc3efb8183e9.png)

**Comment by teelolws** [comment]
https://github.com/teelolws/Altoholic-Classic/issues/18
