### ISSUE TITLE
Account Sharing Request fails

### ISSUE THREAD

**Issue by Kryd0s** [teelolws/Altoholic-Classic#2]
First of all, thank you so much for doing this. You have no idea how much I appreciate it.

One of the main things I use Altoholic for is keeping track of my multiple accounts. Normally you can click Account Sharing Request in the top right, and then send a request for a table of contents from the target character. On the target account (also running altoholic) there is a message in chat about sending table of contents. That doesn't even show up so the two altoholics aren't communicating with each other at all it seems.

I intend to take a look through the code myself, but I'm definitely not an addon author so I have very little idea what I'm doing. Just mainly wanted to say thanks. :)

**Comment by teelolws** [comment]
I actually took out the button in one of my recent pushes, simply because I have no idea how that part of the code works as I've never used it myself. If you want to take a crack at getting it working, go for it. The code is all in there, I just commented out the button to access it!

**Comment by Kryd0s** [comment]
My pull request https://github.com/teelolws/Altoholic-Classic/pull/3 fixes this issue by skipping the datastores that were causing the process to hang.
