### ISSUE TITLE
Searching within the professions module not working.

### ISSUE THREAD

**Issue by rbpaiett** [teelolws/Altoholic-Classic#20]
When a char is clicked on and then you click on the professions button, the search feature on the upper right doesn't work.  As soon as you keystroke any letter, all the items you can create disappear.  Is this feature disabled for now?
![Altoholic Search Issue](https://user-images.githubusercontent.com/1621701/77130213-4a7fc880-6a14-11ea-952f-ac2350ae9a37.jpg)

Even when I were to press 'h' for Heavy Kodo Stew (for example) the results go blank.

**Comment by teelolws** [comment]
Never noticed that search box when I was porting this to classic, tbh. I have an idea what the problem is, I'll fix it when I get a chance.

**Comment by teelolws** [comment]
Allright, got it. I also removed that Item Link button that slipped past my "remove all retail only stuff" filter. 
![image](https://user-images.githubusercontent.com/49792789/77208926-d6533b00-6b61-11ea-83c7-13ca851bfa7c.png)

**Comment by rbpaiett** [comment]
Great!  Is it already in this github version?  I didn't see a twitch update as yet.  I figured you'd get around to it eventually.

**Comment by teelolws** [comment]
I'll only be doing twitch updates when a week has passed since my last update, to give enough time for testing.

**Comment by rbpaiett** [comment]
Not that it's a big deal but the searching is case sensitive, meaning that if you capitalize any word, the search results will blank out, fyi.  This would be a feature thing but not a deal breaker.

**Comment by teelolws** [comment]
Oh Thaoky. Nice one. Was pretty easy to spot the mistake. See if you can:

`if name and string.find(strlower(name), currentSearch, 1, true) then`
