### ISSUE TITLE
Account Summary

### ISSUE THREAD

**Issue by S4mmis** [teelolws/Altoholic-Classic#22]
My account summary page is empty, not show any of my characters

**Comment by teelolws** [comment]
Reset your filters. 
![image](https://user-images.githubusercontent.com/49792789/77304438-51cb0d00-6d59-11ea-9590-614110e0d518.png)

**Comment by S4mmis** [comment]
Have selected all already

**Comment by teelolws** [comment]
Try running these two macros:

/run Altoholic:SetOption("UI.Tabs.Summary.CurrentFactions", 3); Altoholic:SetOption("UI.Tabs.Summary.CurrentLevelsMax", 120);

/run Altoholic:SetOption("UI.Tabs.Summary.CurrentLevelsMin", 1); Altoholic:SetOption("UI.Tabs.Summary.CurrentTradeSkill", 0); Altoholic:SetOption("UI.Tabs.Summary.CurrentClasses", 0);

Then close and reopen the Altoholic window.

If that still doesn't work, close the game and delete the addon Saved Variables:

![image](https://user-images.githubusercontent.com/49792789/77307712-a329cb00-6d5e-11ea-9a19-f5075185c6fd.png)

**Comment by S4mmis** [comment]
those macros works, Thanks mate,
