### ISSUE TITLE
DataStore_Inventory error at login on lvl1 characters

### ISSUE THREAD

**Issue by boohyaka** [teelolws/Altoholic-Classic#23]
My mules have been giving me this error right at login. Only level 1 characters have this error, but all of them as far as I can tell (I have three lvl1 mules with the error, and my four >lvl1 characters don't have it). After closing the initial error everything looks fine. I tried uninstalling and reinstalling Altoholic  with no success. There is no DataStore_Inventory SavedVariable I can delete to try and start fresh, so it being a bug with level 1 characters is my only guess.

Many thanks for taking over Altoholic classic from Thaoky! Much appreciated, it's such a great addon :)

```
Message: integer overflow attempting to store -nan(ind)
Time: Fri Mar 27 01:08:24 2020
Count: 1
Stack: integer overflow attempting to store -nan(ind)
(tail call): ?
[C]: in function `format'
...e\AddOns\DataStore_Inventory\DataStore_Inventory.lua:92: in function <...e\AddOns\DataStore_Inventory\DataStore_Inventory.lua:85>
...e\AddOns\DataStore_Inventory\DataStore_Inventory.lua:265: in function <...e\AddOns\DataStore_Inventory\DataStore_Inventory.lua:263>
[C]: ?
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `SendMessage'
Interface\AddOns\DataStore\DataStore.lua:138: in function <Interface\AddOns\DataStore\DataStore.lua:133>
Interface\AddOns\DataStore\DataStore.lua:258: in function `func'
Interface\AddOns\DataStore\DataStore.lua:275: in function <Interface\AddOns\DataStore\DataStore.lua:266>
[C]: ?
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ce\AddOns\DataStore\libs\AceComm-3.0\AceComm-3.0.lua:264: in function <...ce\AddOns\DataStore\libs\AceComm-3.0\AceComm-3.0.lua:246>

Locals: <none>
```

**Comment by teelolws** [comment]
Unfortunately I can't duplicate this. Just made two characters on my server, no error. Then I made a character on a server I've never played on, no error.

However, I can make an easy fix for this anyway.

Open up Datastore_Inventory, go to Line 92, and add code above and below it to look like this:

![image](https://user-images.githubusercontent.com/49792789/77712789-b3c99200-7039-11ea-88e5-1dd703c74efa.png)

Let me know if that fixes the issue. If it does I'll submit the fix.

**Comment by teelolws** [comment]
If you're feeling adventurous, and want to figure out where the problem is, you could instead change it to:

```
`    print(ail)
    print(UnitName("player"))
    table.insert(out, format("%s:%d", UnitName("player"), ail))`

check your chatlog and see which one is causing the issue.

**Comment by boohyaka** [comment]
I'm happy to help get to the bottom of it if it's useful :)

I have very basic coding knowledge so apologies in advance if I say stupid/obvious things.

Your first fix doesn't work because I think the if (ail) test succeeds. 
print(ail) gives "-nan(ind)"

I tried several things to try and check for that value but didn't manage to do it.

Looking at the code, ail gets the AverageItemLevel of a character. I thought that was it : all my level 1 mules have no items :) they're fully naked, which would explain why ail would get no average value. So I tried to reproduce the issue by creating a new level 1 character and stripping it naked as well, and...it doesn't show the issue :( 

I checked the SavedVariables\DataStore_Inventory.lua file and I see no difference between the new level 1 character I just created and the "old" ones that have the error. It's really weird.

FYI "print(UnitName("player"))" gives "Boohyaka nil". I was surprised about that nil, but all my characters show it, even those that don't have the error on login.

If you want me to try anything else, I'm here!

**Comment by teelolws** [comment]
What I don't understand is: why is that code even being called at all? From what I can tell, its used to send a message to your guild about what gear your characters have. But if you've just made a character, you're not even in a guild. It shouldn't run that at all.

It doesn't for me.

Are you running the game in English? A lot of my "it doesn't happen when I try it" bugs turn out to be specific to the game client being in other languages. Its easy enough for me to switch to another language and try it, but I tried it in French and still no bug.

**Comment by boohyaka** [comment]
ah, good call on the guild thing! my new character wasn't in a guild when my other mules are. that may be the reason. I will try!

yes, my client is in English.

**Comment by teelolws** [comment]
I've noticed the average item level functions are giving everything AILs that don't make sense. Numbers between 0 and 1. Looking into it now.

**Comment by teelolws** [comment]
Okay, this should stop the "nan"s (not a number) from ever getting stored: 

![image](https://user-images.githubusercontent.com/49792789/77746532-e9926900-7081-11ea-8517-c83c51d402a4.png)

The cause was new characters don't have any gear on, so it was calculating its average item level by dividing by zero.

Now I need to add something to remove the ones already stored by previous versions of the addon.

That should be as simple as adding "or 0" here:

![image](https://user-images.githubusercontent.com/49792789/77746671-2a8a7d80-7082-11ea-98b2-9bf80e0c9be1.png)

**Comment by teelolws** [comment]
https://github.com/teelolws/Altoholic-Classic/commit/b88b4912c219d1f911662c61578beaadd12abf64

**Comment by teelolws** [comment]
Whoops. Need to add a bit more to make sure it stores 0 when the character has no gear on.

https://github.com/teelolws/Altoholic-Classic/commit/e15fafc86708aafb8ec0fd450003984d6b2e7254
