### ISSUE TITLE
"Expert" recipe books not recognized

### ISSUE THREAD

**Issue by Painstormx** [teelolws/Altoholic-Classic#24]
There seems to be a minor issue with some of the recipe books, like "Expert First Aid - Under Wraps".
The tooltip for book the shows "Could be learned by" for all my chars even though they already know that book. I'm guessing it's the same for Expert cooking book.
Books like "Manual: Heavy Silk Bandage" seems to okay though.
Looks like it's because the expert books doesn't actually give you a recipe, but just unlocks the 150+ level of the profession.

Altoholic v1.13.014

**Comment by teelolws** [comment]
Mmmm. Because they're "recipe" items but aren't really recipes. I'll have to make a special case for them.

**Comment by teelolws** [comment]
Done. 
![image](https://user-images.githubusercontent.com/49792789/78064400-306bc000-73ee-11ea-9874-1a8d1597f4e5.png)

https://github.com/teelolws/Altoholic-Classic/commit/a465f4b07352cfe5b2b1c31adb1750920c9375c2

**Comment by teelolws** [comment]
Oh yeah, and the cooking and fishing books. None on my servers AH so I can't test if they're working right now. https://github.com/teelolws/Altoholic-Classic/commit/47acd569cd9831f659d58bc24da4a5a68d8d746b
