### ISSUE TITLE
DataStore Errors on Load for all characters

### ISSUE THREAD

**Issue by Malevola** [teelolws/Altoholic-Classic#26]
**Error 1:**
1x DataStore_Agenda\DataStore_Agenda-r30.lua:651: attempt to index global 'C_Calendar' (a nil value)
DataStore_Agenda\DataStore_Agenda-r30.lua:651: in function <DataStore_Agenda\DataStore_Agenda.lua:633>
[C]: ?
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function <FrameXML\UIParent.lua:352>
[C]: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:693: in function <FrameXML\UIParent.lua:658>

**Error 2:**
1x DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PLAYER_TALENT_UPDATE"
[C]: in function `RegisterEvent'
DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: in function `OnUsed'
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:142: in function `RegisterEvent'
...rfaceDataStore_Talents\DataStore_Talents-r62.lua:428: in function <...rfaceDataStore_Talents\DataStore_Talents.lua:426>
[C]: ?
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function <FrameXML\UIParent.lua:352>
[C]: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:693: in function <FrameXML\UIParent.lua:658>

**Comment by teelolws** [comment]
You're either trying to run the Retail version on Classic, or you're running an outdated version.

**Comment by Malevola** [comment]
This was the version downloaded for 1.13.3 from Twitch. Is that one outdated?

**Comment by teelolws** [comment]
The most recent version is here: https://github.com/teelolws/Altoholic-Classic/releases
