### ISSUE TITLE
Recipes not correctly tracked across multiple characters

### ISSUE THREAD

**Issue by Nazgutek** [teelolws/Altoholic-Classic#27]
Depending on which character logged in last, and even then I cannot consistently reproduce behaviour, altoholic will say that either all characters know a recipe, or none. (Yes, I have two hunters)

![image](https://user-images.githubusercontent.com/50041970/79687495-85596400-823f-11ea-9319-8e9ae63b7714.png)

This reckons all characters can make Lobster Stew (only one hunter can), and that all characters cannot make Runn Rum Tuber Surprise (only one hunter can).

![image](https://user-images.githubusercontent.com/50041970/79687522-b89bf300-823f-11ea-830a-ed9cbcb37c13.png)

The second image is from the hunter that cannot make Runn Tum Tuber Surprise, but can make Lobster Stew.

![image](https://user-images.githubusercontent.com/50041970/79687561-0f093180-8240-11ea-9f65-6a1dc6239479.png)

And the third image is from the other hunter that can make Runn Tum, but cannot make Lobster Stew.

This also happens with Engineering (one hunter and the warrior both have engineering), and makes the tooptips on who can learn what recipe largely inaccurate.

**Comment by teelolws** [comment]
Yeah I'm still having issues with it. Heres one I screenshotted yesterday:

![image](https://user-images.githubusercontent.com/49792789/79687703-422dde00-829d-11ea-971e-9c163837dd49.png)

**Comment by teelolws** [comment]
Can you try todays release and let me know if this is still an issue: https://github.com/teelolws/Altoholic-Classic/releases/tag/v1.13.4-015

**Comment by Nazgutek** [comment]
On loading, got an error as detailed below.

I decided to just wipe all the altoholic and datastore lua files in World of Warcraft\_classic_\WTF\Account\ACCOUNT\SavedVariables and I've reloaded. So far, the cooking list and engineering grids looks like it's now working. Checking the AH shows engineering recipes correctly apart from one, Schematic: Mechanical Squirrel, but that now looks like a separate issue?

Awesome work, many thanks!

{
			["message"] = "...terface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:796: attempt to index field '?' (a number value)",
			["count"] = 1,
			["addons"] = "  Swatter, v8.2.6511 (SwimmingSeadragon)\n  Altoholic, vClassic v1.13.4-015\n  AltoholicGrids, vr191\n  AltoholicSummary, vv1.13.013\n  AucAdvanced, v8.2.6471 (SwimmingSeadragon)\n  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)\n  AucScanData, v8.2.6498 (SwimmingSeadragon)\n  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)\n  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)\n  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)\n  AucStatSimple, v8.2.6501 (SwimmingSeadragon)\n  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)\n  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)\n  BeanCounter, v8.2.6505 (SwimmingSeadragon)\n  BetterVendorPrice, vv1.08.00-classic\n  CharacterStatsClassic, v2.4.1\n  DataStore, vv1.13.013\n  DataStoreAuctions, vv1.13-013\n  DataStoreCharacters, vv1.13-013\n  DataStoreContainers, vv1.13-013\n  DataStoreCrafts, vv1.13-013\n  DataStoreInventory, vv1.13-013\n  DataStoreMails, vv1.13-013\n  DataStoreQuests, vv1.13-013\n  DataStoreReputations, vv1.13-013\n  DBMCore, v1.13.41\n  DBMDefaultSkin, v\n  DBMStatusBarTimers, v\n  Details, v\n  DetailsStreamer, v\n  DetailsTinyThreat, v\n  Enchantrix, v8.2.6506 (SwimmingSeadragon)\n  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)\n  GatherMate2, v1.45.5\n  honorspy, v1.7.3\n  Informant, v8.2.6508 (SwimmingSeadragon)\n  Questie, v5.5.1\n  SlideBar, v8.2.6509 (SwimmingSeadragon)\n  Stubby, v8.2.6510 (SwimmingSeadragon)\n  WeaponSwingTimer, v4.1.0\n  BlizRuntimeLib_enUS v1.13.4.11304 <none>\n  (ck=58e)\n",
			["locals"] = "recipeData = 4520751\n_ = 3\nrecipeID = 35318\nisLearned = true\n(*temporary) = 4673025\n(*temporary) = 1\n(*temporary) = \"attempt to index field '?' (a number value)\"\n_GetRecipeInfo = <function> defined @Interface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:695\naddon = <table> {\n SetDefaultModuleLibraries = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:367\n Enable = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:294\n RegisterChatCommand = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceConsole-3.0\\AceConsole-3.0.lua:85\n EnableModule = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:332\n modules = <table> {\n }\n GetModule = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:210\n IterateEmbeds = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:442\n UnregisterComm = <function> defined @Interface\\AddOns\\DataStore\\libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:153\n defaultModuleLibraries = <table> {\n }\n TimeLeft = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceTimer-3.0\\AceTimer-3.0.lua:172\n Deserialize = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceSerializer-3.0\\AceSerializer-3.0.lua:246\n UnregisterChatCommand = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceConsole-3.0\\AceConsole-3.0.lua:111\n ScheduleRepeatingTimer = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceTimer-3.0\\AceTimer-3.0.lua:129\n CancelAllTimers = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceTimer-3.0\\AceTimer-3.0.lua:160\n Printf = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceConsole-3.0\\AceConsole-3.0.lua:69\n SetDefaultModulePrototype = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:409\n Guilds = <table> {\n }\n name = \"DataStore_Crafts\"\n Characters = <table> {\n }\n IsEnabled = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:451\n orderedModules = <table> {\n }\n ScheduleTimer = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceTimer-3.0\\AceTimer-3.0.lua:94\n DisableModule = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:350\n ThisCharacter = <table> {\n }\n defaultModuleState = true\n OnInitialize = <function> defined @Interface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:918\n baseName = \"DataStore_Crafts\"\n RegisterMessage = <function> defined @Interface\\AddOns\\DataStore\\libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:90\n GetArgs = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceConsole-3.0\\AceConsole-3.0.lua:144\n Print = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceConsole-3.0\\AceConsole-3.0.lua:54\n SetupOptions = <function> defined @Interface\\AddOns\\DataStore_Crafts\\Options.lua:7\n IsTradeSkillWindowOpen = <function> defined @Interface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:958\n OnDisable = <function> defined @Interface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:949\n OnEnable = <function> defined @Interface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:936\n IsModule = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:468\n db = <table> {\n }\n SetDefaultModuleState = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:387\n CancelTimer = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceTimer-3.0\\AceTimer-3.0.lua:147\n UnregisterAllComm = <function> defined @Interface\\AddOns\\DataStore\\libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:174\n SetEnabledState = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceAddon-3.0\\AceAddon-3.0.lua:424\n Serialize = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceSerializer-3.0\\AceSerializer-3.0.lua:122\n enabledState = true\n SendCommMessage = <function> defined @Interface\\AddOns\\DataStore\\libs\\AceComm-3.0\\AceComm-3.0.lua:87\n RegisterEvent = <function> defined @Interface\\AddOns\\DataStore\\libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:90\n UnregisterAllMessages = <function> defined @Interface\\AddOns\\DataSto",
			["timestamp"] = "2020-04-20 08:24:56",
			["context"] = "Global",
			["stack"] = "...terface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:796: in function `callback'\n...terface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:737: in function <...terface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:714>\n...terface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:793: in function <...terface\\AddOns\\DataStore_Crafts\\DataStore_Crafts.lua:786>\n(tail call): ?\n...nterface\\AddOns\\Altoholic_Grids\\Grid_Tradeskills.lua:169: in function `ColumnSetup'\nInterface\\AddOns\\Altoholic_Grids\\TabGrids.lua:76: in function `Update'\n[string \"*:OnClick\"]:6: in function <[string \"*:OnClick\"]:1>\n",
		}

**Comment by teelolws** [comment]
This should fix that LUA error: https://github.com/teelolws/Altoholic-Classic/commit/3060a24b4a1ffdf95135222256e4a84dc27a83f9
