### ISSUE TITLE
Schematic: Mechanical Squirrel

### ISSUE THREAD

**Issue by Nazgutek** [teelolws/Altoholic-Classic#28]
SS from warrior with Engineering:

![image](https://user-images.githubusercontent.com/50041970/79726502-cf475600-82e2-11ea-8430-db1f70f5884e.png)

SS from AH:

![image](https://user-images.githubusercontent.com/50041970/79726752-3533dd80-82e3-11ea-9167-6fb31a37d6f8.png)

**Comment by teelolws** [comment]
Ah, theres probably other recipes like this. Its because the item it makes doesn't have the same name as the recipe.

![image](https://user-images.githubusercontent.com/49792789/79796417-9f16ba80-83a9-11ea-9b34-cd52f047a5f1.png)

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Classic/commit/3f5c4b32d76f1c3a40052981d1f85ade286cebbe
