### ISSUE TITLE
Issues with buying recipes.

### ISSUE THREAD

**Issue by VoyseyS** [teelolws/Altoholic-Classic#31]
84x DataStore_Crafts\DataStore_Crafts-v1.13-013.lua:875: attempt to index field '?' (a number value)
DataStore_Crafts\DataStore_Crafts-v1.13-013.lua:875: in function <DataStore_Crafts\DataStore_Crafts.lua:874>
(tail call): ?
Altoholic\Tooltip.lua:264: in function `callback'
DataStore_Crafts\DataStore_Crafts-v1.13-013.lua:737: in function <DataStore_Crafts\DataStore_Crafts.lua:714>
(tail call): ?
Altoholic\Tooltip.lua:262: in function `GetRecipeOwners'
Altoholic\Altoholic-Classic v1.13.4-016.lua:273: in function `MerchantFrame_UpdateMerchantInfo'
FrameXML\MerchantFrame.lua:125: in function `MerchantFrame_Update'
FrameXML\MerchantFrame.lua:90: in function <FrameXML\MerchantFrame.lua:82>
[C]: ?
[C]: in function `Show'
FrameXML\UIParent.lua:2087: in function `SetUIPanel'
FrameXML\UIParent.lua:1932: in function `ShowUIPanel'
FrameXML\UIParent.lua:1793: in function <FrameXML\UIParent.lua:1789>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2535: in function <FrameXML\UIParent.lua:2523>
[C]: in function `ShowUIPanel'
FrameXML\MerchantFrame.lua:29: in function <FrameXML\MerchantFrame.lua:22>

Locals:
recipeID = 35318
(*temporary) = 5431553
(*temporary) = "attempt to index field '?' (a number value)"
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:85
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 UnregisterComm = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Ace3\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:111
 ScheduleRepeatingTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:160
 Printf = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 Guilds = <table> {
 }
 name = "DataStore_Crafts"
 Characters = <table> {
 }
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 ThisCharacter = <table> {
 }
 defaultModuleState = true
 OnInitialize = <function> defined @DataStore_Crafts\DataStore_Crafts.lua:923
 baseName = "DataStore_Crafts"
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:54
 SetupOptions = <function> defined @DataStore_Crafts\Options.lua:7
 IsTradeSkillWindowOpen = <function> defined @DataStore_Crafts\DataStore_Crafts.lua:963
 OnDisable = <function> defined @DataStore_Crafts\DataStore_Crafts.lua:954
 OnEnable = <function> defined @DataStore_Crafts\DataStore_Crafts.lua:941
 IsModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 CancelTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 UnregisterAllComm = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Serialize = <function> defined @Ace3\AceSerializer-3.0\AceSerializer-3.0.lua:122
 enabledState = true
 SendCommMessage = <function> defined @Ace3\AceComm-3.0\AceComm-3.0.lua:87
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 RegisterComm = <function> defined @Ace3\AceComm-3.0\AceComm-3.0.lua:60
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SendMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0

**Comment by teelolws** [comment]
You have some outdated data. Log your characters with professions and open their profession books.
