### ISSUE TITLE
Tracking craft skills

### ISSUE THREAD

**Issue by pighair** [teelolws/Altoholic-Classic#37]
I'm Korean user and craft skill tracking is not working properly.
I'd like to contribute to support Korean but have no idea what I should do.
I tried to update koKR.lua under Datastore_craft/Locales but it looks not helping.

Can you provide any guide or something to localize this addon?

**Comment by teelolws** [comment]
Seems to be working?

![image](https://user-images.githubusercontent.com/49792789/83919292-694d5a00-a7ce-11ea-8b69-c112bbb20a37.png)

![image](https://user-images.githubusercontent.com/49792789/83919306-6f433b00-a7ce-11ea-8a0e-68467b0d28fe.png)

![image](https://user-images.githubusercontent.com/49792789/83919321-766a4900-a7ce-11ea-9f94-25fdd0d8c614.png)

**Comment by pighair** [comment]
For me it is not working in two different ways.

First, it does not recognize my professional skills.
This character has tailoring and herbalism as professional skills but Altoholic shows secondary skills twice.

![WoWScrnShot_060620_091246](https://user-images.githubusercontent.com/18534209/83931483-f47f1d80-a7d7-11ea-93df-a776cb4eddf8.jpg)
![WoWScrnShot_060620_091303](https://user-images.githubusercontent.com/18534209/83931577-6a838480-a7d8-11ea-8f60-8d945297534b.jpg)

Second, it does not tracking craft items well.
Engineering is well displayed (but mining is not displayed and Cooking is displayed twice.)
However craft items are not displayed or displayed under wrong category.
![WoWScrnShot_060620_101339](https://user-images.githubusercontent.com/18534209/83932598-9d307b80-a7de-11ea-9cc4-c3f26496ca68.jpg)
![WoWScrnShot_060620_101619](https://user-images.githubusercontent.com/18534209/83932639-e5e83480-a7de-11ea-8567-c26f1db46202.jpg)

**Comment by teelolws** [comment]
Should be fixed in: https://github.com/teelolws/Altoholic-Classic/compare/3164b36bfb81...1ea2e1ffe4ea

And I've uploaded the patch to Twitch: https://www.curseforge.com/wow/addons/altoholic-classic/files/2974168
