### ISSUE TITLE
Korean localization

### ISSUE THREAD

**Issue by pighair** [teelolws/Altoholic-Classic#38]
1. Popup message for mails in Summary tab are not localized. I tried to fix it for myself but couldn't find where I can fix.
<img width="418" alt="2020-06-08_02-28-57" src="https://user-images.githubusercontent.com/18534209/83975825-e395ef80-a930-11ea-8e4c-cde21739cbeb.png">

2. Please replace translation in attached file koKR.lua in Altoholic/Locales with attached file.
[koKR.txt](https://github.com/teelolws/Altoholic-Classic/files/4742604/koKR.txt)
With current distributed version, user cannot see the remaining date and hours, and expression is not natural. Also there is type with |n and |r.
<img width="1124" alt="2020-06-08_02-39-31" src="https://user-images.githubusercontent.com/18534209/83975894-51dab200-a931-11ea-913d-1554b9aa23a8.png">

**Comment by teelolws** [comment]
They're not coded to be localised in any language.

If you can give me a translation for these phrases, I'll add them:

"[999] will be returned upon expiry"
"Closest return in [3 hours 3 minutes]"
The parts in [] brackets don't need to be translated, only the text around them.

For deleted mail, its a bit more complicated.

I need this phrase:
"19 will be deleted upon expiry."
But I need you to tell me which word or words is "deleted".

**Comment by pighair** [comment]
Because word order in sentence is different between English and Korean, it will be better translation if location of date/time value can be changed.

"Mails found:"
우편 수:

"[999] will be returned upon expiry"
[999]개의 우편 반송 예정

"[999] will be %sdeleted|r upon expiry"
[999]개의 우편 삭제 예정
삭제 is the word for deleted and I put the codes from other text translation.

"Closest return in [3 hours 3 minutes]"
[3 hours 3 minutes] 후 반송됨

"Closest deletion in [3 hours 3 minutes]"
[3 hours 3 minutes] 후 삭제됨

And I missed the color changes in koKR.lua I provided before. Below please find new suggestion with color changes between return and deletion.
I'll provide 2 translations with and without [datetime]. If it is possible to change date/time location, please use translation with [datetime].

without datetime
L["Will be %sdeleted|r in"] = "다음 기한 후 %s삭제|r됨"
L["Will be %sreturned|r in"] = "다음 기한 후 %s반송|r됨"

with datetime
L["Will be %sdeleted|r in"] = "[datetime] 후 %s삭제|r됨"
L["Will be %sreturned|r in"] = "[datetime] 후 %s반송|r됨"

Here's the screenshot of translation without datetime.
<img width="326" alt="2020-06-08_14-17-52" src="https://user-images.githubusercontent.com/18534209/83994957-ea554e80-a992-11ea-9651-1d8a182a2b11.png">

**Comment by teelolws** [comment]
Unfortunately, I can't change the order without moving the code back out of the Localization files.

**Comment by teelolws** [comment]
Try this:
[AddOns.zip](https://github.com/teelolws/Altoholic-Classic/files/4744077/AddOns.zip)

**Comment by pighair** [comment]
Works very well. Thank you.
