### ISSUE TITLE
played time isn't showing

### ISSUE THREAD

**Issue by fadedtimes** [teelolws/Altoholic-Classic#40]
played time isn't showing.
Should I reset the data store?
![WoWScrnShot_060820_102033](https://user-images.githubusercontent.com/52267324/84049280-da794280-a971-11ea-85fe-98fdafe0e12c.jpg)

**Comment by teelolws** [comment]
Do you have this option "Hide real play time" checked?

![image](https://user-images.githubusercontent.com/49792789/84080365-30142480-aa30-11ea-93bf-22bdca11b854.png)

**Comment by fadedtimes** [comment]
exactly what it was
