### ISSUE TITLE
Synchronisation with other Users

### ISSUE THREAD

**Issue by Sarangah** [teelolws/Altoholic-Classic#43]
Since today I'm not able to receive the table of content from linked accounts. The other Person(s) also can't get any content from me.

**Comment by teelolws** [comment]
Got this box checked on both accounts? 

![image](https://user-images.githubusercontent.com/49792789/84950061-5cbbf080-b142-11ea-8f46-db97a28eca30.png)

**Comment by Sarangah** [comment]
Yes, we have. We have each other in the list to always be able to get the table from each other.

**Comment by teelolws** [comment]
You probably have corrupt data. Clear our your saved variables on the account you're sending from, repopulate it, and try again.

Worked when I tried it: 
![image](https://user-images.githubusercontent.com/49792789/85185480-3932aa80-b2e8-11ea-86f5-d224dcc3dab5.png)

**Comment by Sarangah** [comment]
This worked! Thank you so much!
