### ISSUE TITLE
Ongoing account sharing is spamming my chat

### ISSUE THREAD

**Issue by zazomazzo** [teelolws/Altoholic-Classic#45]
First of all thank you soooo much <3 that you are maintaining the addon, it's absolutely vital for me! 

I have enabled account sharing and it is working so far.
But after setting up the "ongoing" sharing, it is spamming my chat with "No player named 'xxx-xxx' is currently playing."
Even when one of the characters IS online, it spams that the other characters are not.

Would be nice to include some kind of "check" if the characters are online before trying to do stuff. :)

Example:
[https://i.imgur.com/9gafpyM.png](https://i.imgur.com/9gafpyM.png)

**Comment by teelolws** [comment]
Don't check the boxes for the other characters until they're actually online.
