### ISSUE TITLE
Localization issue on account sharing

### ISSUE THREAD

**Issue by pighair** [teelolws/Altoholic-Classic#46]
In add-on option "Account Sharing", first character of character name is not displayed in Korean.
<img width="290" alt="2020-07-13_22-18-45" src="https://user-images.githubusercontent.com/18534209/87309215-434a7080-c557-11ea-91eb-0fdbccdb3575.png">

Due to uploading error I added another image on comment.

**Comment by pighair** [comment]
<img width="422" alt="2020-07-13_22-18-31" src="https://user-images.githubusercontent.com/18534209/87309685-e307fe80-c557-11ea-9bcc-cd7f471a9c7e.png">

**Comment by pighair** [comment]
It affects actual feature.

With captured status, it does not automatically send list to 물은셀프's request.
I tried to add manually with one meaningless character like screenshot below, and then the list is sent to 물은셀프's request automatically.
<img width="246" alt="2020-07-13_22-33-35" src="https://user-images.githubusercontent.com/18534209/87310482-fbc4e400-c558-11ea-8ede-e5b6554be34f.png">

**Comment by teelolws** [comment]
Definitely something wrong with korean characters in that field:

![image](https://user-images.githubusercontent.com/49792789/87358623-4e82b800-c5ba-11ea-8b5b-a24b29283bc0.png)
One korean character adds an empty string

![image](https://user-images.githubusercontent.com/49792789/87358653-5cd0d400-c5ba-11ea-9468-246c22ccaf64.png)
One Roman character adds it just fine

Its PROBABLY something to do with it trying to capitalize the first character. But you don't have lowercase / capital letters in korean so its turning the first letter into nothing. I'll try and figure it out.

**Comment by teelolws** [comment]
Confirmed: the problem is with this function: 

![image](https://user-images.githubusercontent.com/49792789/87362487-e2588200-c5c2-11ea-9f0c-464272bc3a3e.png)

Its trying to make the first letter of character names a capital letter and every other letter lower case. Its breaking if the name is Korean (and Chinese) and I don't know how to fix it. I've sent out a request for help and will have to wait until someone responds.

**Comment by teelolws** [comment]
Try this: [Altoholic classic test.zip](https://github.com/teelolws/Altoholic-Classic/files/4915752/Altoholic.classic.test.zip)

**Comment by pighair** [comment]
It's fixed well. Thank you.
