### ISSUE TITLE
Multiple 'Missing entry' errors after latest update.

### ISSUE THREAD

**Issue by rbpaiett** [teelolws/Altoholic-Classic#49]
This is 1 of 20 errors that popped up after the latest update:

All with a similar structure of errors.

2x AceLocale-3.0-6: Altoholic: Missing entry for 'Search Containers'
Altoholic\Altoholic-Classic v1.13.4-024.lua:41: in function <Altoholic\Altoholic.lua:19>
Altoholic\Altoholic-Classic v1.13.4-024.lua:322: in function <Altoholic\Altoholic.lua:321>
[C]: ?
[C]: ?
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:380: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:695: in function <FrameXML\UIParent.lua:658>
[C]: ?

One of the last few errors were like this:

2x DataStore_Characters\Locales\enUS-English (US).lua:4: unexpected symbol near ']'

I would have given more info but there were like 20 more errors like them.

**Comment by rbpaiett** [comment]
I see another update is sent and all is working properly now.

**Comment by teelolws** [comment]
Yeah I switched to using a packager to upload my updates and it was messing some parts up.2
