### ISSUE TITLE
I got a following error once I opened it up

### ISSUE THREAD

**Issue by brunomedice** [teelolws/Altoholic-Classic#5]
The following error was found once I clicked on altoholic icon.
> Date: 2020-01-22 10:01:18
> ID: 10
> Error occured in: Global
> Count: 1
> Message: ...nterface\AddOns\Altoholic_Summary\AccountSummary.lua line 2095:
>    bad argument #3 to 'format' (string expected, got nil)
> Debug:
>    [C]: ?
>    [C]: format()
>    ...nterface\AddOns\Altoholic_Summary\AccountSummary.lua:2095: AiLTooltip()
>    ...nterface\AddOns\Altoholic_Summary\AccountSummary.lua:702:
>       ...nterface\AddOns\Altoholic_Summary\AccountSummary.lua:687
> Locals:

**Comment by teelolws** [comment]
Odd. That suggests that EXPANSION_NAME7 is set to Nil. But when I checked it, it has "BFA".

Can you run this script:

`/script print(EXPANSION_NAME7)`

And tell me what it outputs?

I'll also add "fix some broken Average Item Level code" to my todo list.

**Comment by brunomedice** [comment]
Nil

**Comment by teelolws** [comment]
Well its strange that it outputs "BFA" for me, but "nil" for you.

I'll just take out the EXPANSION_NAME code since its not needed anyway when I have some time. I'm currently tied up with Ny'alotha.

**Comment by brunomedice** [comment]
I'd wish know lua better... I'm Dev myself but not sure about this lua
thing.

**Comment by teelolws** [comment]
Its not really an LUA thing. EXPANSION_NAME7 is just a global constant that stores "BFA". Its set by the game / blizzard, not by the LUA. For some reason your game client has "nil" while mine has "BFA".

Its still redundant, best I remove references to it completely.

**Comment by teelolws** [comment]
Just pushed some changes that should fix this. Can you test and confirm it worked please.

**Comment by brunomedice** [comment]
Sorry dude I could not checked before, I'm downloading right now. Thanks
for your help.

Bruno Medice Mariano
0424 747 318
