### ISSUE TITLE
Profession not updated when opened while another is already open

### ISSUE THREAD

**Issue by SpareSimian** [teelolws/Altoholic-Classic#50]
Long-time Altoholic user in retail. I just started loading characters and my 19 Tauren warrior with blacksmithing and mining doesn't show mining as profession two in the skills panel. Secondary skills populated but it took a couple tries. (First aid and fishing didn't populate right away after opening the first aid panel. I equipped a fishing pole, closed and re-opened Altoholic, and then those two populated.) I'm loading many more characters, others with gathering, so I'll report any patterns I see. 

After logging out, I see the mining data in DataStore_Crafts but I don't see anything for blacksmithing.

**Comment by teelolws** [comment]
Gathering skills should be added as soon as you login. Crafting skills won't be populated until you open the profession book.

Fishing populates as soon as you login, but Cooking and First Aid need you to open their crafting books.

This is just a limitation of how Classic works.

**Comment by SpareSimian** [comment]
I think an additional issue is that the data is gathered only if you explicitly close the profession window, either by clicking the X or clicking the action button for the profession. If you open a _different_ profession window, closing the first, the data isn't gathered. I think this is what was biting me with that first character. I was rapidly opening all the professions in series but never explicitly closing any of them. They closed implicitly when I opened another, and that doesn't work.

**Comment by teelolws** [comment]
Yes, thats right. Theres no way for the addon to detect when you switch from one profession from another.

**Comment by SpareSimian** [comment]
I've since populated 10 characters in a different account with no issues. I went back and explicitly opened and closed each profession on the first account and it populated the data properly. So perhaps a documentation issue? I'll go check the wiki...

**Comment by SpareSimian** [comment]
I think I see the issue. In DataStore_Crafts.lua's OnTradeSkillShow, no data is collected if addon.isOpen. I'll bet the close event doesn't fire when you open one profession when another is already open, so the new profession is blown off.

**Comment by SpareSimian** [comment]
It looks like you could remove the line "if (addon.isOpen) then return end" in the two OnOpen functions that skip scanning if the profession window is already open.

**Comment by teelolws** [comment]
Thats there because I was having issues with Tailoring and Enchanting overwriting each other. Because Enchanting uses a different UI, you can actually have both open at the same time.

![image](https://user-images.githubusercontent.com/49792789/88634089-09a66780-d10a-11ea-84ad-6bf7cc1d4b85.png)

I also see that addon.isOpen is used to check that a profession window is currently open when a "skill up message" occurs. Thats probably because I couldn't find any other way to be sure.

I'll do some experimenting with addon.isOpen

**Comment by teelolws** [comment]
Allright, give this a try: https://github.com/teelolws/Altoholic-Classic/releases/tag/1.13.5.025BETA

**Comment by teelolws** [comment]
https://github.com/teelolws/Altoholic-Classic/commit/34184ff230a7077034606956b6dd2b1ba3f9f48f

**Comment by SpareSimian** [comment]
That  looks good. I deleted my DataStore_Crafts.lua* files and hit all the profession buttons in sequence without closing any and it populated the data properly.
