### ISSUE TITLE
Account sharing dialog needs a close button

### ISSUE THREAD

**Issue by SpareSimian** [teelolws/Altoholic-Classic#51]
It's not obvious how to get out of it. Cancel does it, but a close button would be more intuitive. (Minor cosmetic enhancement.)

**Comment by teelolws** [comment]
I agree. Thaoky made that, and I'm not a UI developer so I don't know how to add a close button to it.

**Comment by teelolws** [comment]
Allright, done. I also made the entire window click-and-draggable while I was there, cause that was annoying me.

![image](https://user-images.githubusercontent.com/49792789/89470831-d2eae400-d7d0-11ea-9bec-b8c485701c88.png)
