### ISSUE TITLE
Many Classic features appear to be broken after 1.13 patch

### ISSUE THREAD

**Issue by fireboy92k** [teelolws/Altoholic-Classic#52]
At least in my case, I can no longer see things like professions, equipped, bank, etc. for all my various chars.

**Comment by teelolws** [comment]
Screenshots?

**Comment by fireboy92k** [comment]
![Untitled](https://user-images.githubusercontent.com/56378639/88994570-b0c80200-d2b6-11ea-98a0-b6a18a9f89e5.png)

**Comment by teelolws** [comment]
Did you turn off to uninstall some of the modules? That looks like you don't have Datastore_containers installed or turned on.

**Comment by fireboy92k** [comment]
Ah, good catch.  I had looked and 'DataStore' was turned on, but I didn't click into it.  All the submodules were off.   That seems to have fixed it!

Now in looking the ones under the primary Altaholic are loaded 'on demand'.  SHould i be loading them as well?

**Comment by teelolws** [comment]
Nah. They'll load automatically when needed. Long as you don't have them unchecked/disabled.

**Comment by fireboy92k** [comment]
Thanks!
