### ISSUE TITLE
No Gnomeregan reputation

### ISSUE THREAD

**Issue by SpareSimian** [teelolws/Altoholic-Classic#55]
The reputation grid shows grey for the Gnomeregan row. None of my ten toons shows any. If I'm reading the code right, I should see entries for [3] in the Datastore_Reputations wtf file and I don't see that entry for any of them. So it looks like that reputation isn't getting collected. I do see it non-zero in the reputation tab of my Blizzard character panel.

**Comment by SpareSimian** [comment]
The correct faction name is "Gnomeregan Exiles", in line 63 of DataStore_Reputations.lua. That fixed it for me.

**Comment by teelolws** [comment]
Yeah just figured that out. Fixing it now.

**Comment by teelolws** [comment]
It was renamed to Gnomeregan in a future patch, and I don't play alliance so I never noticed I needed to change it back for Classic.

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/Altoholic-Classic/compare/cf83de171210...b77035794f63

**Comment by teelolws** [comment]
Thankfully the old names were still in LibBabbleFaction, so I don't have to hunt down the names in other languages.
