### ISSUE TITLE
Feature Request:  Faction Filter matching current character

### ISSUE THREAD

**Issue by rbpaiett** [teelolws/Altoholic-Classic#58]
Is it possible for the Faction Filter to match the faction of the current character automatically?  Every time I go from Horde to Alliance, I have to manually change the Faction Filter to match my current character.  I could have sworn this was happening in previous versions but I could be mistaken.

**Comment by teelolws** [comment]
Sure. I'll add this for classic only, though, since its a lot more restrictive about cross-faction collections than Retail is.

Added in: https://github.com/teelolws/Altoholic-Classic/compare/28e6b9a9adf9...4a21cc6dddaf

**Comment by rbpaiett** [comment]
Thank you very much!
