### ISSUE TITLE
Level, Gold, Time totals misaligned

### ISSUE THREAD

**Issue by Mizzajl** [teelolws/Altoholic-Classic#63]
at the bottom right corner:

![image](https://user-images.githubusercontent.com/31535978/90975343-98ed4200-e533-11ea-9876-a68fd520bf7c.png)

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/90990957-9523f300-e5f9-11ea-9e8a-0348cd22dcbc.png)

Added in: https://github.com/teelolws/Altoholic-Classic/commit/729130b221a8a4ae4327cd8703be435fba3559a8
