### ISSUE TITLE
German localisation - no trade skill information

### ISSUE THREAD

**Issue by voyvoy** [teelolws/Altoholic-Classic#64]
Hi,

when I play with the English client, all trade skills are shown correctly. But when I switch to German client, some skills are in the wrong column and there is no detailed information in the tooltip either.

Wrong column (cooking, for example):
![grafik](https://user-images.githubusercontent.com/10220573/91687486-1e8a7680-eb60-11ea-97b7-0cf84b7793a4.png)

Tooltip doesn't show details (should be skill level 57 + recipes):
![grafik](https://user-images.githubusercontent.com/10220573/91687523-38c45480-eb60-11ea-94ad-eeb5e54c5405.png)

**Comment by teelolws** [comment]
If you switch between languages you need to rescan everything again. Just log the alt, open the profession books.

**Comment by voyvoy** [comment]
Unfortunately, your suggestion didn't work. It seems there is only a partial update. For example, four out of six characters have first aid, yet no skill is displayed (I opened up all skill windows on each character). For the other skills the tooltips still display 0/0 skill despite - in this case alchemy - the skill has been leveled. Some skills - herbalism at the first character or fishing at pretty much every character  - aren't shown at all (although that's perhaps by design since there is no profession window to open?).

![grafik](https://user-images.githubusercontent.com/10220573/91729910-84e5b800-eba5-11ea-895e-89e844948fe5.png)

I didn't switch languages recently, I have been playing on the German client for weeks now. But since I haven't used the skill tab before, I didn't notice the missing update. At first I assumed there was something blocking the update/overwrite of data, so I removed the addon and installed it newly. (Perhaps I missed a file?) Then I switched language to test and in the English client the updates are done correctly every time I open a skill tab. Back to the German client and it's not updating completely.

**Comment by teelolws** [comment]
Just delete your DataStore_Crafts saved variable file and start it over. You've filled it up with English data.

You'll find it in your WoW Classic folder\_classic_\WTF\Account\_ACCOUNT NAME_\SavedVariables

**Comment by voyvoy** [comment]
I deleted all datastore files and logged in. I opened the craft windows in order of the two main crafts first. Both worked and show up now. Then I went on to cooking - nothing. First aid is the same. (Not sure how fishing updates, perhaps when I skill up?)

![grafik](https://user-images.githubusercontent.com/10220573/91767307-399acc00-ebdc-11ea-9ee0-cbdcde2d3733.png)

I tested it on a second character - first the main skills, then the secondary. Same result. Then I went to a third character who has two main professions (skinning/lw), and opened cooking and first aid first - they show up in the main skill column now:

![grafik](https://user-images.githubusercontent.com/10220573/91767664-cb0a3e00-ebdc-11ea-8e7d-f2c52281c18e.png)

Afterwards I opened the trade skill window for leather working, but it doesn't show in the list. It looks as if something prevents the secondary trade skill column from showing skills properly (or at all).

**Comment by teelolws** [comment]
If it doesn't show up the first time, open the spellbook again. Classic has a bug where not everything is visible the first time you open a profession book.

**Comment by teelolws** [comment]
Fishing issue fixed in: https://github.com/teelolws/Altoholic-Classic/compare/123c4cee2f56...88b0219eaf9d
It was only checking for your fishing skill in English.

**Comment by voyvoy** [comment]
Detecting fishing works now with the newest version, thank you! 
I deleted all files again in saved variables, deactivated all addons aside from altoholic and opened the first character. Fishing skill was there already.
![grafik](https://user-images.githubusercontent.com/10220573/91794716-14c64900-ec1c-11ea-92bd-1178990b7e65.png)

Then I opened first aid and this happened:
![grafik](https://user-images.githubusercontent.com/10220573/91794772-2b6ca000-ec1c-11ea-8866-5d276c9a43d1.png)

After that, no matter what trade skill I opened and how often I re-opened it, nothing else was added to the grid aside from the number 66 which is the skill level of crafting poisons (it's a rogue character). At this point I'm pretty much out of ideas especially since I never had this problem in the English version.

**Comment by teelolws** [comment]
Okay I see the problem. The DataStore_Crafts locale file is missing translations. Fill this in with the german names of the professions and I'll upload it:
[deDE.zip](https://github.com/teelolws/Altoholic-Classic/files/5153987/deDE.zip)

**Comment by voyvoy** [comment]
Can't upload files it seems, so here's the text.

L["Fishing"] = "Angeln"
L["Alchemy"] = "Alchimie"
L["Blacksmithing"] = "Schmiedekunst"
L["Enchanting"] = "Verzauberkunst"
L["Engineering"] = "Ingenieurskunst"
L["Leatherworking"] = "Lederverarbeitung"
L["Tailoring"] = "Schneiderei"
L["Skinning"] = "Kürschnerei"
L["Mining"] = "Bergbau"
L["Herbalism"] = "Kräutersammeln"
L["Smelting"] = "Verhüttung"
L["Cooking"] = "Kochkunst"
L["First Aid"] = "Erste Hilfe"
L["Poisons"] = "Gifte"
L["Beast_Training"] = "Wildtierausbildung"

**Comment by teelolws** [comment]
Thanks. Added in: https://github.com/teelolws/Altoholic-Classic/commit/3c1e4f00dca17152998b8b0ff57b2e66e0401e1d
