### ISSUE TITLE
Feature request: Attunement tracking

### ISSUE THREAD

**Issue by Painstormx** [teelolws/Altoholic-Classic#65]
Hi,
Since you seem to be pretty active with keeping the addon working (and thank you for that), I got a suggestion if you run out of stuff to do :)
It would be awesome to be able to track completed and in-progress attunements, for each char.
I can never remember which char that has done the BWL attunement or exactly where a char is on the Onyxia attunement.
Something that could show each step/quest and maybe show Not started, In progress, Done or something like that.
It's not a huge problem right now, but in TBC there's a massive amount of quests, dungeons, items etc. needed for each attunment chain.

**Comment by teelolws** [comment]
Done. The "B" means my Drakefire Amulet is in the bank.

![image](https://user-images.githubusercontent.com/49792789/92171325-7e9a5900-ee8f-11ea-9603-341ed88fa382.png)

I'm too Horde to test if it works properly for Alliance, unfortunately.

Added in: https://github.com/teelolws/Altoholic-Classic/commit/ce34f465869bc33463945ab5aaf6ac6bd060b66d

**Comment by Painstormx** [comment]
Very nice, seems to be fine on my Alliance chars :)
I hope it can be expanded upon later, so you can maybe click on the icon and see where you are in an attunement quest chain, if it's not completed yet.
Will definitely be very handy in TBC with the very long chains there.
