### ISSUE TITLE
Error at Auctions House?

### ISSUE THREAD

**Issue by ghost** [teelolws/Altoholic-Classic#66]
Hello! 
WoW Classic
When I click on an item on the left in the auction house, it also shows the info window of my equipment for comparison, but the info window closes again after 2 seconds and no comparison is possible.
Is it possible to change the attitude?
Should I send screenshot?

**Comment by teelolws** [comment]
Yes, screenshot please.

**Comment by HeGoWork** [comment]
Thank you for your feedback, Below the screenshot

With fairy greetings HeGoWork

Von: teelolws <notifications@github.com> 
Gesendet: Freitag, 18. September 2020 11:23
An: teelolws/Altoholic-Classic <Altoholic-Classic@noreply.github.com>
Cc: HeGoWork <h.hego@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [teelolws/Altoholic-Classic] Error at Auctions House? (#66)

 

Yes, screenshot please.

**Comment by teelolws** [comment]
You need to open the Github page and upload the screenshot there.

**Comment by HeGoWork** [comment]
Sorry my English is very bad how do I upload the screenshot ? I can't find a button for it

**Comment by teelolws** [comment]
Just paste it in here. You can paste pictures into this textbox.

**Comment by HeGoWork** [comment]
![WoWScrnShot_091820_104202-A](https://user-images.githubusercontent.com/71492616/93596496-b3db9680-f9b9-11ea-9ac0-cbd58f895ce5.jpg)

**Comment by teelolws** [comment]
What Auction House addon is that?

**Comment by HeGoWork** [comment]
Auction house with Addon Auctioneer Suite WoW Classic, The error only comes when I use AddOn Althoholic, if I turn off the Altoholic addon then the window remains open normally

**Comment by HeGoWork** [comment]
The error also comes when I turn off the AddOn Auctioneer, i.e. use the standard Action House

**Comment by teelolws** [comment]
Must be a different addon interfering with it. I've tested it with my game in German, it does the item compare with no problems:

![image](https://user-images.githubusercontent.com/49792789/93600269-760b5c00-fa13-11ea-999b-341b1b8f9182.png)

**Comment by HeGoWork** [comment]
Ok thanks

 

Von: teelolws <notifications@github.com> 
Gesendet: Freitag, 18. September 2020 15:01
An: teelolws/Altoholic-Classic <Altoholic-Classic@noreply.github.com>
Cc: HeGoWork <h.hego@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [teelolws/Altoholic-Classic] Error at Auctions House? (#66)

 

Must be a different addon interfering with it. I've tested it with my game in German, it does the item compare with no problems:

 <https://user-images.githubusercontent.com/49792789/93600269-760b5c00-fa13-11ea-999b-341b1b8f9182.png>

**Comment by HeGoWork** [comment]
Problem solved, I uninstalled the addon, thanks for the review
bye bye

**Comment by SpareSimian** [comment]
What addon did you uninstall?

**Comment by teelolws** [comment]
Mine, probably.
