### ISSUE TITLE
Agenda - Mooncloth cooldown name

### ISSUE THREAD

**Issue by Painstormx** [teelolws/Altoholic-Classic#69]
Just a very minor issue.
But the text in the Agenda tab shows the cooldown on Mooncloth as "Tailoring".
Should say "Mooncloth" instead since it's not the entire profession that's on cooldown ;)
That will also be helpful later where more than this one specific craft can be on cooldown.

**Comment by teelolws** [comment]
Ahh thats because its designed around the TBC cloths that all share a cooldown.

Easy enough fix: https://github.com/teelolws/Altoholic-Classic/commit/eef9e453c21e59c50fac6c5dd049094fbd2238da
