### ISSUE TITLE
tradeskill cooldowns

### ISSUE THREAD

**Issue by beren12** [teelolws/Altoholic-Classic#7]
Is there any way to track trade skill cool downs like transmutes, moon cloth, and refined deep rock salt? If not, could you maybe take a look at https://www.wowinterface.com/downloads/info11581-Broker_TradeCooldowns.html please?

**Comment by teelolws** [comment]
[You mean such as the way it always has and still does?](https://imgur.com/a/1d7qCkH)

**Comment by beren12** [comment]
No I wasn't clear. I meant listing them in the data broker plugin (it's part of core.lua), and/or with a popup telling you an alt's cool down is ready.
