### ISSUE TITLE
Feature Request:  Appraiser Module - Items up for auction be a different color.

### ISSUE THREAD

**Issue by rbpaiett** [teelolws/Altoholic-Classic#70]
So, when I open up Altoholic (Classic) and use the Appraiser, sometimes I check to see items I have up for auction by checkmarking "Auction" at the top of the list on the left.  As it is right now, the only way I can tell if something is up for auction instead of in inventory is the number of items listed is 'slightly' faded in comparison to the items in inventory.

What I'd like is to have that number be a different color (like blue maybe) instead of 'slightly faded'.  I can barely see the difference.  Perhaps there's an easier way to indicate an item up for auction that can be programmed easier, I'm just not sure.

Anyway, that's what I'd like.

**Comment by teelolws** [comment]
Can you show me a couple screenshots? Show me what it is currently (so I can see what you're referring to) and point me to which part you want changed.

**Comment by rbpaiett** [comment]
Ok, here we have Altoholic with the Appraiser Tab clicked.
On the left the 'Auctions' slot has been selected so it shows both inventory & auctioned items.

<img width="470" alt="Altoholic Appraiser 01" src="https://user-images.githubusercontent.com/1621701/94324396-9628a700-ff4e-11ea-8504-06693f966c73.png">

1.  This item here is up for auction and the background is a little darker and the number count slightly faded.
2.  These two items are in the inventory and the background is slightly lighter.

This is a bit too subtle for me to notice and even at first I thought it was just the number of items was slightly darker.

Anyway, my thinking was to make any item in the Auction House be a different color but quite a bit more obvious.  The contrast between inventory and the auction house is much too subtle, almost not noticeable.

Any help to make them more visible would be helpful.

**Comment by teelolws** [comment]
Dude, thats not Altoholic. Thats some Auction House addon.

**Comment by rbpaiett** [comment]
Oh, you're right, I'll redirect the issue to the proper channels.
