### ISSUE TITLE
When logging in to a character with Salt Shaker cooldown < 1 day the event is reset.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [teelolws/Altoholic-Classic#74]
Steps to reproduce:
1. Log in to a character with a Salt Shaker cooldown.
2. Use the Salt Shaker.
3. Log out.
4. Log in to another character.
5. Verify the CD event is set correctly.
6. Do NOT log in to the character for ~2 days.
6. Wait until < 1 day and > 0 days remain on the CD.
7. Log in to the character with the CD.
8. Log out. Log in to another character.
9. The event is set to ~51 days.

The mage, priest, and rogue all have their Salt Shaker CDs up at ~09:41 on Wednesday October 14th but their event is set to ~23:41 on Monday November 30th.
[https://i.imgur.com/hNGcJMX.jpg](https://i.imgur.com/hNGcJMX.jpg)

**Comment by teelolws** [comment]
Yeah theres definitely something wrong here.

![image](https://user-images.githubusercontent.com/49792789/95689317-5c54e180-0c6c-11eb-8e87-f993c0696f41.png)

**Comment by teelolws** [comment]
Looking like this is a bug in WoW: item cooldowns are tracked based on your computers uptime, and if you restart your computer, it keeps tracking the cooldown relative to the old uptime. With no way to get that old uptime, it becomes garbage information. I probably won't be able to fix this.

**Comment by teelolws** [comment]
Heres what I'll do, as a "workaround": if it detects you've restarted your PC, its just not going to list the item. Thats the best I can do until Blizzard one day fixes this bug.
