### ISSUE TITLE
VersionID incorrect

### ISSUE THREAD

**Issue by GovtGeek** [teelolws/Altoholic-Classic#75]
The latest addon version number fails due to it being incorrectly set.

`## Version: Classic-v1.13.5-047` versus `## Version: @project-version@` (Classic-v1.13.5-049)

```
Error occured in: Global
Count: 1
Message: ..\AddOns\Altoholic\Core.lua line 10:
   attempt to concatenate local 'versionID' (a nil value)
Debug:
   Altoholic\Core.lua:10: in main chunk
```

**Comment by teelolws** [comment]
Whoops. Forgot to commit that fix.

Fixed in https://github.com/teelolws/Altoholic-Classic/commit/ace26edea5b52dd234f91f5db8f8f6a369e020fe
