### ISSUE TITLE
Please revert this change. Some cooldown texts are not displayed anymore.

### ISSUE THREAD

**Issue by schroeg** [teelolws/Altoholic-Classic#76]
Hi

Could you please revert the change in DataStore_Containers/DataStore_Containers.lua, since it is not needed for this addon:

```
-- Credit to Arkoniel and Eliot from the WoW Addons discord for this code.
-- Something to do with the time returned by GetItemCooldown being bugged if your machine has been fully restarted since using the item
local function GetCooldownLeft(start, duration)
    if start < GetTime() then
        local cdEndTime = start + duration
        local cdLeftDuration = cdEndTime - GetTime()        
        return cdLeftDuration
    end
    local time = time()
    local startupTime = time - GetTime()    
    local cdTime = (2 ^ 32) / 1000 - start
    local cdStartTime = startupTime - cdTime
    local cdEndTime = cdStartTime + duration
    local cdLeftDuration = cdEndTime - time    
    return cdLeftDuration
end

-- *** Scanning functions ***
-- This is a fix for item cooldown icons displaying incorrectly when the computer has been rebooted
-- Not really relevant to DataStore, just thought it would be helpful to leave it here anyway
-- Basically a bugfix for problems on Blizzards end
hooksecurefunc( getmetatable(CreateFrame("Cooldown")).__index, "SetCooldown", function(s,c,d,r)
    if c < GetTime() then return end
    local e = (GetTime() + ( (2^32) / 1000  - c ))
    s:SetCooldownUNIX(time()-e,d, 1/1000)
end)
```

Due to this change some cooldown texts are briefly visible and then not showing anymore.
I have notices this lately during a raid that sometimes the cooldown text is not shown. E.g The cooldown of the stacking debuf from Firemaw was not showing, so I could not see how long I need to wait before the debuf did fall off.
Tested it with some of my own buffs. e.g. Fire Ward or Frost Ward. The cooldown text is shown briefly and then removed.

Seen it with the cooldown text with ElvUI or with using OmmiCC.

If I remove this change or disable DataStore_Containers then it works normally.

```
Revision: 483433f5e33a8fefca6e866d0b4a2f41bd209aca
Author: teelolws <49792789+teelolws@users.noreply.github.com>
Date: 14-10-2020 5:51:50
Message:
Fix for Salt Shaker showing wrong event time after a system reboot

----
Modified: Altoholic/Altoholic.toc
Modified: Altoholic/Events.lua
Modified: DataStore_Containers/DataStore_Containers.lua

```

**Comment by teelolws** [comment]
Try this: https://github.com/teelolws/Altoholic-Classic/commit/44e1e8b22affd65692a987d1d9e740eba2c61593

Released in: https://www.curseforge.com/wow/addons/altoholic-classic/files/3085899

**Comment by schroeg** [comment]
Hi

I have checked with latest version Classic-v1.13.5-052.

My own buffs cooldown are shown again on the unitframes (Player and/or Target).

To check the debuff cooldown text from raid bosses I need to week until next week raid reset.
I will let you know if it is fixed correctly.

**Comment by schroeg** [comment]
Hi

I did a AQ40 & BWL raid run this week. The buff/debuff cooldown texts are shown again on the unitframes.
