### ISSUE TITLE
current update is having problems showing gear in search

### ISSUE THREAD

**Issue by SunTzuTech1** [teelolws/Altoholic-Classic#77]
I got some lua errors in the current version.   None of my searches for gear is working.  Gonna have to revert to a previous version.

Message: ...terface\AddOns\DataStore_Agenda\DataStore_Agenda-r30.lua:651: attempt to index global 'C_Calendar' (a nil value)
Time: Wed Oct 21 15:27:54 2020
Count: 1
Stack: ...terface\AddOns\DataStore_Agenda\DataStore_Agenda-r30.lua:651: attempt to index global 'C_Calendar' (a nil value)
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:630: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

-----------------

Message: ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PLAYER_TALENT_UPDATE"
Time: Wed Oct 21 15:27:54 2020
Count: 1
Stack: ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "PLAYER_TALENT_UPDATE"

Locals: <none>

------------------
Message: ...rface\AddOns\DataStore_Talents\DataStore_Talents-r62.lua:182: attempt to call global 'GetMaxTalentTier' (a nil value)
Time: Wed Oct 21 15:27:56 2020
Count: 1
Stack: ...rface\AddOns\DataStore_Talents\DataStore_Talents-r62.lua:182: attempt to call global 'GetMaxTalentTier' (a nil value)

Locals: <none>

-----------------

Message: Interface\AddOns\DataStore_Stats\DataStore_Stats-r32.lua:50: Usage: GetCombatRating(ratingIndex)
Time: Wed Oct 21 15:27:56 2020
Count: 7
Stack: Interface\AddOns\DataStore_Stats\DataStore_Stats-r32.lua:50: Usage: GetCombatRating(ratingIndex)

Locals: <none>

-------------------
Message: ...terface\AddOns\DataStore_Crafts\DataStore_Crafts-r83.lua:644: bad argument #2 to 'strsplit' (string expected, got table)
Time: Wed Oct 21 15:31:20 2020
Count: 6
Stack: ...terface\AddOns\DataStore_Crafts\DataStore_Crafts-r83.lua:644: bad argument #2 to 'strsplit' (string expected, got table)

Locals:

**Comment by teelolws** [comment]
You've installed the retail version of DataStore. Don't do this; it won't run on Classic. Everything you need is in the .zip files at https://www.curseforge.com/wow/addons/altoholic-classic/files 
Don't install any other versions of DataStore or its modules.

**Comment by SunTzuTech1** [comment]
will roll back to the latest version.  Thanks for the clarification.
