### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Nawake234** [teelolws/Altoholic-Classic#78]
Hello, i have one bug, it appears when i log one character.

what is the problem? thx :)

Error occured in: Global
Count: 1
Message: ..\AddOns\DataStore_Stats\DataStore_Stats.lua line 50:
   Usage: GetCombatRating(ratingIndex)
Debug:
   (tail call): ?
   [C]: GetCombatRating()
   DataStore_Stats\DataStore_Stats.lua:50:
      DataStore_Stats\DataStore_Stats.lua:27
   DataStore_Stats\DataStore_Stats.lua:109:
      DataStore_Stats\DataStore_Stats.lua:108
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  Altoholic, vClassic-v1.13.5-053
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  BagBrother, v
  BagFreeSpaceCounter, v1.0.2
  Bagnon, v9.0.3
  BagnonScrap, v8.3.0
  Bartender4, v4.10.5
  buffOmat, v1.82
  CharacterStatsClassic, v3.6.5
  ClassicAuraDurations, v1.13.61
  ClassicCastbars, vv1.3.13
  ClassicCastbarsOptions, v
  DataStore, vv1.13.013
  DataStoreAgenda, vr31
  DataStoreAuctions, vv1.13-013
  DataStoreCharacters, vv1.13-013
  DataStoreContainers, vv1.13-013
  DataStoreCrafts, vv1.13-013
  DataStoreInventory, vv1.13-013
  DataStoreMails, vv1.13-013
  DataStoreQuests, vv1.13-013
  DataStoreReputations, vv1.13-013
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v1.13.61
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7.1
  Details, v
  Dismounter, v1.2.1
  Dominos, v9.0.12
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  GatherMate2, v1.45.6-classic
  honorspy, v1.7.7
  IceHUD, v1.13.0-2
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LibHealComm40, v
  Mapster, v1.9.0
  MikScrollingBattleText, v5.7.149
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  NeatPlates, v1.13.5.17
  NeatPlatesBlizzardPlates, v2.0
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v9.0.2
  oRA3, vv4-classic
  Portfolio, v1.21
  Prat30, v3.9.1
  Prat30Libraries, v
  Quartz, v3.5-classic-5
  Questie, v6.1.0
  Scrap, v9.0.1
  SexyMap, vv5-classic
  ShadowedUFNotMyAuras, vv0.1.3
  ShadowedUnitFrames, vv4.2.3-Classic
  Spy, v1.1.2
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.24
  TinyTooltip, v8.2.1
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  WIM, v3.8.15
  BlizRuntimeLib_frFR v1.13.5.11305 <none>
  (ck=8d5)

**Comment by teelolws** [comment]
You've somehow installed DataStore_Stats on Classic. That is currently a Retail-only module.

**Comment by Nawake234** [comment]
Lol i have installed the version of 09/02/2020 ^^.

I have delete all datastore / altoholic and redownload all.

It's all good Thx :)
