### ISSUE TITLE
Agenda and cooldowns

### ISSUE THREAD

**Issue by Painstormx** [teelolws/Altoholic-Classic#79]
Using v1.13.5-053.
A couple of issues.
1) The Salt Shaker cooldown doesn't show immediately. I have to do a /reload.
2) A transmute cd, like Arcanite, just shows up as "Alchemy". It should show what is actually on cd.

**Comment by teelolws** [comment]
For 1: This cannot be changed. Its not necessary, anyway. You're on the character and you just put the Salt Shaker on cooldown. You already know what its cooldown is!

For 2: This is by design, because it puts ALL your alchemy transmutes on cooldown, not just Arcanite!

**Comment by Painstormx** [comment]
Well, about the Salt Shaker...
The problem is that when I just log out on the char that is doing that one, none of my other chars can see it on the Agenda, since it only updates on /reload or relog on the specific char.
Since that char is only logged once every 3 days for the Salt Shaker cd, I never see it on the Agenda.
So I am actually forced to do a /reload before I log out so that the cd is saved for the other chars to see it.
Can't test it right now since I'm on cd, but pretty sure that is how it works.

**Comment by teelolws** [comment]
Oh I see what you mean. I'll get DataStore_Containers to update on the BAG_UPDATE_COOLDOWN event.

**Comment by teelolws** [comment]
This should sort that out: https://github.com/teelolws/Altoholic-Classic/commit/aa9e59dd834afdc898b13cfe3349a4f3c4be0a0c

My Salt Shaker doesn't come off cooldown for 3 days, so I can't test if it worked right now.

While I was there I also added the current/next battleground weekend to the calendar.

**Comment by teelolws** [comment]
Doing a test:

![image](https://user-images.githubusercontent.com/49792789/98653565-0fb31200-23a2-11eb-8ba6-e89852e75615.png)

![image](https://user-images.githubusercontent.com/49792789/98653586-1477c600-23a2-11eb-8582-796d04ac9d0d.png)

![image](https://user-images.githubusercontent.com/49792789/98653614-1c376a80-23a2-11eb-959d-cac3d8462286.png)

![image](https://user-images.githubusercontent.com/49792789/98653651-278a9600-23a2-11eb-871e-ec44d0acb775.png)

Then quickly logging out and checking on another character:

![image](https://user-images.githubusercontent.com/49792789/98653805-5bfe5200-23a2-11eb-9c34-33a11e14a2a9.png)


Seems to be fixed!
