### ISSUE TITLE
Cancel this: was conflict with WhoHas/Poss....

### ISSUE THREAD

**Issue by urodoc** [teelolws/Altoholic-Classic#80]
As soon as something is typed into the "Search containers" box and enter is hit, error window pops up:

Date: 2020-11-06 22:52:48
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Altoholic_Search\Search.lua line 666:
   attempt to compare number with nil
Debug:
   Altoholic_Search\Search.lua:666:
      Altoholic_Search\Search.lua:651
   Altoholic_Search\Search.lua:749:
      Altoholic_Search\Search.lua:746
   Altoholic_Search\Search.lua:849: FindItem()
   [string "*:OnEnterPressed"]:2:
      [string "*:OnEnterPressed"]:1
Locals:
character = "Default.Pagle.Hhm"
itemID = nil
itemLink = nil
itemCount = nil
containers = <table> {
 VoidStorage = <table> {
 }
 Bag10 = <table> {
 }
 Bag0 = <table> {
 }
 Bag8 = <table> {
 }
 Bag100 = <table> {
 }
 Bag3 = <table> {
 }
 Bag7 = <table> {
 }
 Bag5 = <table> {
 }
 Bag4 = <table> {
 }
 Bag-2 = <table> {
 }
 Bag1 = <table> {
 }
 Bag2 = <table> {
 }
 Bag9 = <table> {
 }
 Bag11 = <table> {
 }
 Bag6 = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 VoidStorage = <table> {
 }
 Bag10 = <table> {
 }
 Bag0 = <table> {
 }
 Bag8 = <table> {
 }
 Bag100 = <table> {
 }
 Bag3 = <table> {
 }
 Bag7 = <table> {
 }
 Bag5 = <table> {
 }
 Bag4 = <table> {
 }
 Bag-2 = <table> {
 }
 Bag1 = <table> {
 }
 Bag2 = <table> {
 }
 Bag9 = <table> {
 }
 Bag11 = <table> {
 }
 Bag6 = <table> {
 }
}
(for control) = "VoidStorage"
containerName = "VoidStorage"
container = <table> {
 size = 0
 bagtype = 0
 ids = <table> {
 }
 cooldowns = <table> {
 }
 freeslots = 0
 counts = <table> {
 }
 links = <table> {
 }
}
bagNum = nil
(*temporary) = "dStorage"
(*temporary) = nil
(*temporary) = 4
(*temporary) = "dStorage"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
currentResultType = 1
PLAYER_ITEM_LINE = 1
currentResultKey = "Default.Pagle.Hhm"
currentResultLocation = nil
L = <table> {
 Druid of the Fang (Trash Mob) = "Druid of the Fang (Trash Mob)"
 World PVP = "World PVP"
 Guild Bank Remote Update = "Guild Bank Remote Update"
 Artisan = "Artisan"
 COLUMN_RESTXP_DETAIL_3 = "It is achieved in 10 days."
 Uncollected resources = "Uncollected resources"
 Goldthorn = "Goldthorn"
 Heroic Mode Tokens = "Heroic Mode Tokens"
 Level 70 Reputation PVP = "Level 70 Reputation PVP"
 Scourge Invasion = "Scourge Invasion"
 Shared = "Shared"
 Food = "Food"
 Master = "Master"
 Revanchion = "Revanchion"
 and above = "and above"
 Guild Communication Enabled = "Guild Communication Enabled"
 Tablet of Will = "Tablet of Will"
 Gordok Brewery = "Gordok Brewery"
 Find Upgrade = "Find Upgrade"
 Alliance Forces = "Alliance Forces"
 Shift-Click to link this info = "Shift-Click to link this info"
 Mountain Silversage = "Mountain Silversage"
 %s has received a mail from %s = "%s has received a mail from %s"
 Beast Training = "Beast Training"
 Non Set Leather = "Non Set Leather"
 Not started = "Not started"
 Armbreaker Huffaz = "Armbreaker Huffaz"
 Ethereum Prison = "Ethereum Prison"
 Characters = "Characters"
 Firebloom = "Firebloom"
 Blizzard Collectables = "Blizzard Collectables"
 Requesting %s information from %s = "Requesting %s information from %s"
 Classes: Mage = "Classes: Mage"
 Gently Shaken Gift = "Gently Shaken Gift"
 COLUMN_BAGS_SUBTITLE_1 = "Your main inventory slots"
 FILTER_LEVELS = "Level filter"
 %s has no bids = "%s has no bids"
 Source = "Source"
 COLUMN_BANK_SUBTITLE_1 = "Your bank inventory slots"
 Hallow's End = "Hallow's End"
 Muddy Churning Waters = "Muddy Churning Waters"
 Send account sharing request to: = "Send account sharing request to:"
 Ooze Covered Rich Thorium Vein = "Ooze Covered Rich Thorium Vein"
 Reference data received (%s) ! = "Reference data received (%s) !"
 Clear goblin AH entries = "Clear goblin AH entries"
 Olaf = "Olaf"
 Warn when mail expires in less days than this value = "Warn when mail expires in less days than this value"
 Rare Fish = "Rare Fish"
 Gold Vein = "Gold Vein"
 Poisons = "Poisons"
 Update current tab from = "Update current tab from"
 COLUMN_RESTXP_SUBTITLE = "Click to toggle 100%/150% mode"
 Suggested leveling zone:  = "Suggested leveling zone: "
 COLUMN_MONEY_SUBTITLE_4 = "Can't buy happiness .. but buys loads of mounts !"
 TALENT_SPECIALIZATION_UNKOWN = "This talent specialization in unknown.\nActivate it to let the add-on learn about it."
 Honor points:  = "Honor points: "
 (has bids) = "(has bids)"
  days ago = " days ago"
 Last collected = "Last collected"
 Item Level = "Item Level"
 COLUMN_PROFESSION_2
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Altoholic, vClassic-v1.13.5-052
  AltoholicSearch, vv1.13-013
  AltoholicSummary, vv1.13.013
  Armory, vv1.7.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  DataStore, vv1.13.013
  DataStoreAgenda, vr31
  DataStoreAuctions, vv1.13-013
  DataStoreCharacters, vv1.13-013
  DataStoreContainers, vv1.13-013
  DataStoreCrafts, vv1.13-013
  DataStoreInventory, vv1.13-013
  DataStoreMails, vv1.13-013
  DataStoreQuests, vv1.13-013
  DataStoreReputations, vv1.13-013
  DataStoreTalents, vr62
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  GatherMate2, v1.45.6-classic
  Grail, v112
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v33302
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v33302
  GrailReputationsclassic, v007
  Informant, v8.2.6374 (SwimmingSeadragon)
  Pawn, v2.4.4
  Possessions, vr16
  Questie, v6.1.0
  QuestLogEx, v1.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WhoHas, v8.0.0 r06
  Wholly, v079
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=592)

**Comment by teelolws** [comment]
WhoHas hasn't been updated since 2014, doesn't have an official Classic port, and won't have been updated around significant changes to Altoholic over the years. You should defintiely uninstall it.
