### ISSUE TITLE
Agenda showing PvP entries for low-level alt

### ISSUE THREAD

**Issue by SpareSimian** [teelolws/Altoholic-Classic#81]
My level 1 banker alt has PvP events listed in her agenda. I've logged into other alts much higher, none of who appear here.

![wow-altoholic-agenda-20201112](https://user-images.githubusercontent.com/1709928/99070717-9ebc5780-2565-11eb-8d24-4b46ffb203d8.png)

**Comment by teelolws** [comment]
This is intentional. Those are the current and upcoming Bonus Honour Weekends. I wanted a way to see them in-game on Classic. Sure your character is too low level to participate but that doesn't mean you can't level up and join them.

**Comment by SpareSimian** [comment]
It's not that the character is too low but that it was odd that it was the only character showing that. Or is that supposed to be an account-wide entry and you just pick a single character to represent it?

**Comment by teelolws** [comment]
Yup. I needed to attach it to a character to display correctly, so its just attached to whatever is logged in at the time.
