### ISSUE TITLE
Has support for CurseForge been abandoned?

### ISSUE THREAD

**Issue by rbpaiett** [teelolws/Altoholic-Classic#82]
I usually right click on the addon in the CurseForge app for 'View Addon Website' and it seems to have disappeared.  Is this version being abandoned or is there problem with support going on?

Please advise

**Comment by teelolws** [comment]
Unfortuantely, Curseforge decided they will no longer host my fork of the addon.

I'm still maintaining and making the code available here, though for Classic at least, there hasn't been anything to change in a while!

**Comment by rbpaiett** [comment]
Ok then, I have an small, low-impact issue to report.  I'll post it as soon as I've gathered all the info.
