### ISSUE TITLE
Calendar & Side List Not Matching Dates

### ISSUE THREAD

**Issue by rbpaiett** [teelolws/Altoholic-Classic#83]
This is not a big deal but the screenshot here shows on the left of the calendar, the list says Wednesday, April 1st but the Calendar shows the 1st on Thursday.
<img width="718" alt="Altoholic Agenda Issue" src="https://user-images.githubusercontent.com/1621701/113500876-60a0df80-94d6-11eb-9624-969fbeac84e4.png">

**Comment by teelolws** [comment]
Good catch! This should fix it: https://github.com/teelolws/Altoholic-Classic/commit/af3ffa7178fee42aedc48a6746189d760aed3182

v059 is now available here: https://github.com/teelolws/Altoholic-Classic/releases/tag/Classic-v1.13.6-059
