### ISSUE TITLE
Lots of tooltip errors in latest version

### ISSUE THREAD

**Issue by Painstormx** [teelolws/Altoholic-Classic#9]
Just pulled the latest version, but getting a lot of tooltip errors in different places (browsing AH, mouseover spell etc.).
Worked fine previously.

Date: 2020-02-07 15:08:46
ID: 1
Error occured in: Global
Count: 4
Message: ..\AddOns\Altoholic\Tooltip.lua line 301:
   attempt to concatenate field '?' (a nil value)
Debug:
   Altoholic\Tooltip.lua:301:
      Altoholic\Tooltip.lua:272
   Altoholic\Tooltip.lua:322:
      Altoholic\Tooltip.lua:316
   Altoholic\Tooltip.lua:340:
      Altoholic\Tooltip.lua:333
   Altoholic\Tooltip.lua:552:
      Altoholic\Tooltip.lua:510
   Altoholic\Tooltip.lua:634:
      Altoholic\Tooltip.lua:619
   [C]: ?
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:498: OnTooltipSetItem()
   Enchantrix\EnxMain.lua:232:
      Enchantrix\EnxMain.lua:228
   [C]: ?
   [C]: ?
   [C]: SetAction()
   ..\FrameXML\ActionButton.lua:803: ActionButton_SetTooltip()
   [string "*:OnEnter"]:5:
      [string "*:OnEnter"]:1
   [C]: ?
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:266:
      ..\FrameXML\SecureHandlers.lua:263
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:322:
      ..\FrameXML\SecureHandlers.lua:306
   (tail call): ?
Locals:
character = "Default.Pyrewood Village.Candiká"
searchedID = 13443
charCount = 4
account = "Default"
realm = "Pyrewood Village"
char = "Candiká"
name = "Candiká"
isOtherAccount = false
isOtherRealm = false
t = <table> {
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 0
 2 = 0
 6 = 0
 7 = 4
}
(for control) = 7
k = 7
v = 4
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
}
(*temporary) = ""
(*temporary) = nil
(*temporary) = ": 4"
(*temporary) = ""
(*temporary) = "4"
(*temporary) = "attempt to concatenate field '?' (a nil value)"
itemCounts = <table> {
 1 = 0
 2 = 0
 6 = 0
 7 = 4
}
THIS_ACCOUNT = "Default"
THIS_REALM = "Pyrewood Village"
colors = <table> {
 cyan = ""
 recipeOrange = ""
 Horde = ""
 Alliance = ""
 gold = ""
 common = ""
 classMage = ""
 orange = ""
 red = ""
 epic = ""
 rare = ""
 recipeGreen = ""
 battleNetBlue = ""
 heirloom = ""
 teal = ""
 uncommon = ""
 lightBlue = ""
 classHunter = ""
 legendary = ""
 grey = ""
 green = ""
 darkred = ""
 yellow = ""
 recipeGrey = ""
 white = ""
}
itemCountsLabels = <table> {
 1 = "Bags"
 2 = "Bank"
 3 = "AH"
 4 = "Equipped"
 5 = "Mail"
 6 = "Currency"
}
addon = <table> {
 GetItemNameFromRecipeLink = <function> defined @Interface\AddOns\Altoholic\Altoholic.lua:508
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 UnbindViewFromController = <function> defined @Interface\AddOns\Altoholic\libs\LibMVC-1.0\LibMVC.lua:150
 ToggleOption = <function> defined @Interface\AddOns\Altoholic\Frames\TabOptions.lua:142
 EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 UnregisterComm = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SetLastAccountSharingInfo = <function> defined @Interface\AddOns\Altoholic\Altoholic.lua:97
 AccSharingHandler = <function> defined @Interface\AddOns\Altoholic\Comm.lua:125
 RestoreOptionsToUI = <function> defined @Interface\AddOns\Altoholic\Frames\TabOptions.lua:349
 ThisCharacter = <table> {
 }
 OnShow = <function> defined @Interface\AddOns\Altoholic\Altoholic.lua:374
 db = <table> {
 }
 Printf = <function> defined @Interface\AddOns\DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 baseName = "Altoholic"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 OnTimeToNextWarningChanged = <function> defined @Interface\AddOns\Altoholic\Altoholic.lua:658
 OnUpdate = <function> defined @Interface\AddOns\Altoholic\Frames\TabOptions.lua:440
 GetLastAccountSharingInfo = <function> defined @Interface\AddOns\Altoholic\Altoholic.lua:103
 defaultModuleState = true
 UpdateMyMemoryUsage = <function> defined @Interface\AddOns\Altoholic\Frames\TabOptions.lua:415
 IsEnabled = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 TimerFrame = AltoholicTimerFrame {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 SetupOptions = <function> defined @Interface\AddOns\Altoholic\Frames\TabOptions.lua:154
 SetOption = <function> defined @Interface\AddOns\Altoholic\Frames\TabOptions.lua:136
 Loots = <table> {
 }
 GetGuild = <function> defined @Interface\AddOns\Altoholic\Altoholic.lua:86
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 U

**Comment by teelolws** [comment]
This was caused by some code expecting void storage and reagent bank counters. Fixed.

**Comment by Painstormx** [comment]
Seems fixed now :)
